# permissions for end users to edit trainedmodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trainedmodel-editor-role
rules:
  - apiGroups:
      - serving.kubeflow.org
    resources:
      - trainedmodels
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - serving.kubeflow.org
    resources:
      - trainedmodels/status
    verbs:
      - get
