# permissions for end users to view trainedmodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trainedmodel-viewer-role
rules:
  - apiGroups:
      - serving.kubeflow.org
    resources:
      - trainedmodels
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - serving.kubeflow.org
    resources:
      - trainedmodels/status
    verbs:
      - get
