apiVersion: wmlserving.ai.ibm.com/v1
kind: ServingRuntime
metadata:
  name: custom-runtime-pullerless
spec:
  containers:
    - env:
        - name: MODEL_DIRECTORY_PATH
          value: /models
        - name: MODEL_SERVER_MEM_REQ_BYTES
          valueFrom:
            resourceFieldRef:
              containerName: modelserver
              resource: requests.memory
      image: wcp-ai-foundation-team-docker-virtual.artifactory.swg-devops.com/msp-ml-server:0.1.0_20210512-2
      name: modelserver
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "5"
          memory: 1Gi
  grpcDataEndpoint: port:8001
  grpcEndpoint: port:8001

  # Disabled storage helper
  storageHelper:
    disabled: true

  supportedModelTypes:
    - name: ml-type1
      version: "1"
