name: Unit Test

on:
  pull_request:
    branches: [ main ]        

jobs:
  unittest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build develop image
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud update
        ibmcloud -v
        #./scripts/build_devimage.sh
    - name: Run unit test
      run: |
        export CI=true
        ibmcloud login --apikey ${{ APIKEY }} --no-region
        ibmcloud target -r ${{ REGION }} -o ${{ ORGANIZATION }} -s ${{ SPACE }} -g default
        ibmcloud ks cluster config -c ${{ CLUSTER_NAME }}
        kubectl get ns
        #        ./scripts/develop.sh make test
