name: Unit Test

on:
  pull_request:
    branches: [ main ]        

jobs:
  unittest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build develop image
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud update
        ibmcloud -v
        ./scripts/build_devimage.sh
    - name: Run unit test
      run: |
        export CI=true
        ./scripts/develop.sh make test
